spring:
  application:
    name: dashboard-financeiro

  datasource:
    url: jdbc:mysql://localhost:3306/dashboard_financeiro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 271121
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: 8f2a9c4e7b1d6f3a5e8c0b4d7f1a3e6c9b2d5f8a1c4e7b0d3f6a9c2e5b8d1f4a
  expiration-ms: 86400000

ai:
  provider: groq
  api-key: ${GROQ_API_KEY:}
  base-url: https://api.groq.com/openai/v1
  model: llama-3.3-70b-versatile